use_pretrained: False
batch_size: 1
sample_rate: 16000

model:
  n_q: 16
  codebook_size: 256
  latent_space_dim: 256

dataset_args:
  base_path: "/home/ste/Datasets"
  train: "train-clean-100"
  test: "test-clean"
  download: True
  segment_length: 48000
  

optimizers:
  lr: 1e-4
  b1: 0.5
  b2: 0.9

losses: 
  discriminators: True
  sisdr: False
  sisnr: False
  reconstruction: True
# TRAINING ARGS

wandb:
  # artifact_url: "sciapponi/soundphi/model-ms6bl4dt:v86"
  artifact_url: null
  project: "soundphi"

logger: csv

trainer:
  max_steps: 2000000
  accelerator: gpu
  devices: 1
